# Kickstart container config file - see https://gitub.com/infracamp/kickstart
# Run ./kickstart.sh to start a development-container for this project
version: 1
from: "infracamp/kickstart-flavor-gaia:testing"

apache_fallback_resource: "/index.php"

env:


command:
  dev:
    - "sudo npm install gulp-cli -g"
    - "npm install -D --no-bin-links"
    - curl https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
    - sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
    - sudo apt update
    - sudo apt-get install -y google-chrome-unstable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst  --no-install-recommends

    - "sudo -E npm install -g puppeteer node-qunit-puppeteer"
    - "composer install"
   # - "gulp build"
    - "D:gulp watch"


  test:
    - node-qunit-puppeteer www/tests/**/*
