# Kickstart container config file - see https://gitub.com/infracamp/kickstart
# Run ./kickstart.sh to start a development-container for this project
version: 1
from: "infracamp/kickstart-flavor-gaia:testing"

apache_fallback_resource: "/index.php"

command:
  dev:
    - "sudo npm install gulp-cli -g"
    - "npm install -D --no-bin-links"
    - "composer install"
    - "gulp build"
    - "D:gulp watch"